# Generated by Django 4.0.4 on 2022-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('delivery_score', models.BigIntegerField(blank=True, null=True)),
                ('item_url', models.CharField(blank=True, max_length=255, null=True)),
                ('main_category', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('price_today', models.CharField(blank=True, max_length=255, null=True)),
                ('price_yesterday', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_score', models.BigIntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('size_score', models.BigIntegerField(blank=True, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('rate', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
