# Generated by Django 4.0.4 on 2022-04-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calc',
        ),
    ]
